### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Journalify
email: hrishipatel99@gmail.com
description: Your new personal journaling companion
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mobileapplandingpage.learn.uno" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: "#efeeff"
twitter_username: hrishi_55
github_username: hrishi1999
author: Hrishi Patel
logo: assets/images/large-logo.png
twitter:
  username: hrishi_55
social:
  name: Hrishi Patel
  links:
    - https://twitter.com/hrishi_55
    - https://www.linkedin.com/in/hrishi-patel-ba8476140/
    - https://github.com/hrishi1999

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
