name: Journalify
description: Your personal journaling companion and much more!
full_description: "Journalify is a clean, minimalistic, and distraction-free diary app. Track what you want to record about your life, like personal or daily activities, your health, and mood, TV shows you watch, by creating a mood update. Had no time to add mood updates throughout the day? Don't worry, just add a Daily Summary and you are good. Journalify's analytics give you weekly and monthly graphs of your moods and events, for self-discovery. 
<br/>
Features:
<br/>
<br/>
✏️Add a Mood Update regularly, like hourly or so. Mood Updates will help you track your mood and activities throughout the day.
<br/>
📝Add a Daily Summary: Too busy to update mood hourly? Don't worry, just create a Daily Summary at the end of the day and you are all set.
<br/>
🏆Daily Challenges: Challenge yourselves and be a better you! ⚠️ Some challenges might make you seek discomfort!
<br/>
📊Analytics: Track your mood and activities through the week or month (coming soon). Know what makes you happy and what upsets you. 
<br/>
📃Timline: View all your mood updates, daily challenges, and daily summaries here. 
<br/>
🔔Get Motivated: Running out of motivation? *Ting* Get Motivated by notifications! You will feel a bit better :)

Contact us at: hi.journalify@gmail.com"
android: https://play.google.com/store/apps/details?id=com.picle.journalify&ah=JhE7s-eV9IfebQrtFWKWjpRu3ew
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
